# Generated by Django 4.1.7 on 2023-04-28 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
